{% set name = "haystack-bm25" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/haystack_bm25-{{ version }}.tar.gz
  sha256: eeb6c60f9f8bca430236ff7a98f9f0cb6fb13bed5df5630dbe9e0f88c264a706

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.7
    - numpy

test:
  imports:
    - haystack_bm25
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepset-ai/rank_bm25
  summary: Various BM25 algorithms for document ranking
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - masci
